extends:
  - airbnb
  - plugin:react/recommended
plugins:
  - react
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  browser: true
  node: true
  es6: true
rules: {}
  # Add your custom rules here
settings:
  react:
    version: detect
