root: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
settings:
  react:
    version: "detect"
plugins:
  - react
  - import
rules:
  "import/no-extraneous-dependencies": "off"
ignorePatterns:
  - "/__test__/"
